### ISSUE TITLE
Current API_URL returns `contributions` as an empty array for everyone?

### ISSUE THREAD

**Issue by swoppy** [grubersjoe/react-github-calendar#48] opened 2023-07-15 03:46 UTC
`https://github-contributions-api.jogruber.de/v4/{username}`

even the GitHub calendar from website demo/docs do not load.

**Comment by gwynbleiddrivia** [comment] 2023-07-15 12:31
Yes, it returns an empty array right now

**Comment by thatbeautifuldream** [comment] 2023-07-15 13:01
yes the contributions are empty the calender broke

**Comment by grubersjoe** [comment] 2023-07-15 13:03
Hey. Thanks for reporting this. I'm traveling this weekend, but will fix it on Monday. Sorry for the inconvenience.

**Comment by woohyun1031** [comment] 2023-07-15 15:46
If you don't mind, can you tell me later where the problem is?

**Comment by notnotrachit** [comment] 2023-07-15 17:58
Hey, I fixed the issue, I have created a [PR](https://github.com/grubersjoe/github-contributions-api/pulls) for the same in [github-contributions-api](https://github.com/grubersjoe/github-contributions-api) .  

React-github-calendar should work as soon as the PR gets merged in the main API repo. 

Looks like GitHub changed one minor thing in the naming of the classes.

**Comment by masterneko** [comment] 2023-07-16 00:22
I had also made my own API ([https://gh-contrib-api.netlify.app](https://gh-contrib-api.netlify.app)) which uses GitHub's GraphQL library. It's fairly slow and made worse due to no caching.

https://gist.github.com/masterneko/b41c0e1886bafdabbc45558ad0ae74b4

**Comment by grubersjoe** [comment] 2023-07-16 18:51
Hey. It's fixed now. Thanks for the MR @notnotrachit

**Closed by grubersjoe** 2023-07-16 18:51 UTC
